export enum CaseStatus {
  DETECTED = 'DETECTED',
  ANALYZING = 'ANALYZING',
  RECOMMENDED = 'RECOMMENDED',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  APPROVED = 'APPROVED',
  EXECUTING = 'EXECUTING',
  RECOVERED = 'RECOVERED',
  FAILED = 'FAILED',
  STOPPED = 'STOPPED',
  ESCALATED = 'ESCALATED',
}

export enum EventType {
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  SUBSCRIPTION_HALTED = 'SUBSCRIPTION_HALTED',
  CHARGEBACK_INITIATED = 'CHARGEBACK_INITIATED',
}

export enum ActionType {
  EMAIL_REMINDER = 'EMAIL_REMINDER',
  SMS_REMINDER = 'SMS_REMINDER',
  WHATSAPP_MESSAGE = 'WHATSAPP_MESSAGE',
  PAYMENT_LINK = 'PAYMENT_LINK',
  RETRY_CHARGE = 'RETRY_CHARGE',
  PAUSE_SUBSCRIPTION = 'PAUSE_SUBSCRIPTION',
  CANCEL_SUBSCRIPTION = 'CANCEL_SUBSCRIPTION',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
}
